namespace DotRecast.Recast.Demo.Tools;

public enum TestNavmeshToolMode
{
    PATHFIND_FOLLOW,
    PATHFIND_STRAIGHT,
    PATHFIND_SLICED,
    DISTANCE_TO_WALL,
    RAYCAST,
    FIND_POLYS_IN_CIRCLE,
    FIND_POLYS_IN_SHAPE,
    FIND_LOCAL_NEIGHBOURHOOD,
    RANDOM_POINTS_IN_CIRCLE
}
